// 成就篇章定义
export interface Chapter {
  prefix: string;
  label: string;
  max: number;
}

export interface AchievementEntry {
  id: string;
  name: string;
  desc: string;
  img: string;
}

// 15个篇章
export const CHAPTERS: Chapter[] = [
  { prefix: 'RE', label: '初遇篇', max: 30 },
  { prefix: 'DA', label: '日常篇', max: 80 },
  { prefix: 'WI', label: '愿望篇', max: 49 },
  { prefix: 'LO', label: '感情篇', max: 100 },
  { prefix: 'TR', label: '旅行篇', max: 50 },
  { prefix: 'ME', label: '记忆篇', max: 40 },
  { prefix: 'IL', label: '病情篇', max: 60 },
  { prefix: 'TI', label: '时光篇', max: 31 },
  { prefix: 'SP', label: '特殊事件篇', max: 25 },
  { prefix: 'OB', label: '物件篇', max: 25 },
  { prefix: 'EM', label: '情绪篇', max: 40 },
  { prefix: 'FU', label: '葬礼篇', max: 30 },
  { prefix: 'AF', label: '余生篇', max: 30 },
  { prefix: 'HI', label: '隐藏篇', max: 20 },
  { prefix: 'FI', label: '终章', max: 1 },
];

export const TOTAL_ACHIEVEMENTS = 611;

// 格式化成就ID: 前缀_三位数字
function pad(n: number): string {
  return String(n).padStart(3, '0');
}

export function makeId(prefix: string, num: number): string {
  return `${prefix}${pad(num)}`;
}

// 成就原始数据: [编号, 名称, 描述, 图片URL]
type RawEntry = [number, string, string, string];

const RE_DATA: RawEntry[] = [
  [1, '门铃响了', '她站在门口，像小时候一样。', 'https://i.postimg.cc/yYQMv6yG/RE1.png'],
  [2, '好久不见', '"......好久不见。"', 'https://i.postimg.cc/8PK2tkm0/RE2.png'],
  [3, '没变的眼睛', '那双淡蓝色的眼睛，和记忆里一模一样。', 'https://i.postimg.cc/FsWMDFVq/RE3.png'],
  [4, '变了的她', '她比记忆中安静了太多。', 'https://i.postimg.cc/Z5W1gkwM/RE4.png'],
  [5, '愿望清单', '"我有一些想做的事，你能陪我吗？"', 'https://i.postimg.cc/dVhzXMWc/RE5.png'],
  [6, '第一个承诺', '你说了"好"。', 'https://i.postimg.cc/vZ4pjRPb/RE6.png'],
  [7, '旧照片', '翻出了小时候一起拍的照片。', 'https://i.postimg.cc/CxRWtyv1/RE7.png'],
  [8, '对门的灯', '你注意到她家的灯，很久没亮这么晚了。', 'https://i.postimg.cc/L8GrFy7S/RE8.png'],
  [9, '熟悉的味道', '她身上还是小时候那种淡淡的洗衣液味道。', 'https://i.postimg.cc/0yhL1t3N/RE9.png'],
  [10, '纸鹤', '在抽屉里找到了她以前塞给你的纸鹤。', 'https://i.postimg.cc/52DZWPGj/RE10.png'],
  [11, '第一次出门', '休学以来，她第一次主动走出家门。', 'https://i.postimg.cc/vZCpwPj7/RE11.png'],
  [12, '并肩走', '两个人走在路上，影子重叠在一起。', 'https://i.postimg.cc/5tvD4Bd3/RE12.png'],
  [13, '她的速度', '她走得比以前慢了，但你没有催她。', 'https://i.postimg.cc/cJYPxRyz/RE13.png'],
  [14, '便利店', '在便利店买了两根冰棍，和小时候一样。', 'https://i.postimg.cc/jjNBxHYY/RE14.png'],
  [15, '旧公园', '回到小时候一起玩过的公园。', 'https://i.postimg.cc/j5bmLDtG/RE15.png'],
  [16, '秋千', '她坐在秋千上，你在后面推。', 'https://i.postimg.cc/fLNpJVMw/RE16.png'],
  [17, '第一次笑', '她笑了。真正的、发自内心的笑。', 'https://i.postimg.cc/hj1wxKGS/RE17.png'],
  [18, '黄昏回家', '夕阳把两个人的影子拉得很长。', 'https://i.postimg.cc/V6WTMzNr/RE18.png'],
  [19, '晚安', '"晚安。明天见。"', 'https://i.postimg.cc/gJH5RG0R/RE19.png'],
  [20, '等她的消息', '你躺在床上，等着手机亮。', 'https://i.postimg.cc/3RF6p3wZ/RE20.png'],
  [21, '凌晨的消息', '凌晨两点，她发来"你睡了吗"。', 'https://i.postimg.cc/VvshW2SB/RE21.png'],
  [22, '旧昵称', '她叫了你小时候的外号。', 'https://i.postimg.cc/vT8KtC1P/RE22.png'],
  [23, '你也没变', '"你还是和小时候一样。"', 'https://i.postimg.cc/BbZzBR8R/RE23.png'],
  [24, '小挎包', '你注意到她总是背着那个小挎包。', 'https://i.postimg.cc/FzF6Vwd4/RE24.png'],
  [25, '药的声音', '包里传来什么东西碰撞的声音，她迅速把拉链紧了。', 'https://i.postimg.cc/RhCYL269/RE25.png'],
  [26, '第一个疑问', '什么时候开始觉得不对劲的？', 'https://i.postimg.cc/tJrMSDPK/RE26.png'],
  [27, '岔开话题', '你问她最近怎么样，她笑着说"挺好的"。', 'https://i.postimg.cc/rshPngxy/RE27.png'],
  [28, '她的画', '她拿出了画本，里面画满了风景。', 'https://i.postimg.cc/kGjp1wKR/RE28.png'],
  [29, '画里的你', '翻到最后几页，有你的侧脸速写。', 'https://i.postimg.cc/c1T2L1jD/RE29.png'],
  [30, '第一天结束', '8月1日，故事的第一页。', 'https://i.postimg.cc/Df5HwfD9/RE30.png'],
];

const DA_DATA: RawEntry[] = [
  [1, '早安', '"早上好。"', 'https://i.postimg.cc/yY4jKM6L/DA1.png'],
  [2, '一起吃早餐', '对门端来的粥，或者你端过去的面包。', 'https://i.postimg.cc/xjb5WfQ7/DA2.png'],
  [3, '一起吃午餐', '点了两份外卖，坐在客厅地板上吃。', 'https://i.postimg.cc/c4yhWp1D/DA3.png'],
  [4, '一起吃晚餐', '路边的小馆子，或者自己做的。', 'https://i.postimg.cc/9F5b26XN/DA4.png'],
  [5, '一起吃宵夜', '夜里饿了，泡了两碗面。', 'https://i.postimg.cc/RV7RZgN4/DA5.png'],
  [6, '给她做饭', '第一次试着给她做饭。', 'https://i.postimg.cc/SN6rxgJR/DA6.png'],
  [7, '她夸你好吃', '"......比想象中好吃。"', 'https://i.postimg.cc/tC354BYt/DA7.png'],
  [8, '她说难吃', '"你确定这能吃？"但她吃完了。', 'https://i.postimg.cc/Z5jxr08D/DA8.png'],
  [9, '一起洗碗', '站在水槽前面，肩膀碰着肩膀。', 'https://i.postimg.cc/8zwmhsRx/DA9.png'],
  [10, '看电影', '在沙发上看了一部电影。', 'https://i.postimg.cc/bvJHL8LY/DA10.png'],
  [11, '她靠过来了', '看着看着，她的头歪到了你的肩上。', 'https://i.postimg.cc/R0FQG9GQ/DA11.png'],
  [12, '一起打游戏', '她打游戏意外地好。', 'https://i.postimg.cc/Gp5P5NSM/DA12.png'],
  [13, '她赢了', '"我赢了哦。"', 'https://i.postimg.cc/R0D1D8DM/DA13.png'],
  [14, '你赢了', '她不服气地说"再来一局"。', 'https://i.postimg.cc/d1ZRPBbv/DA14.png'],
  [15, '一起听歌', '一人一只耳机。', 'https://i.postimg.cc/hjQ8Wrkh/DA15.png'],
  [16, '她喜欢的歌', '她放了一首以前没听过的歌给你。', 'https://i.postimg.cc/C5yGF80z/DA16.png'],
  [17, '一起看书', '安静地坐在一起，各看各的。', 'https://i.postimg.cc/PJGWtDHy/DA17.png'],
  [18, '念给她听', '你把书里的句子念出声来。', 'https://i.postimg.cc/Gtkk9phC/DA18.png'],
  [19, '一起散步', '没有目的地，就是走。', 'https://i.postimg.cc/Wprm55mn/DA19.png'],
  [20, '遛弯偶遇猫', '路边有一只猫，她蹲下来看了很久。', 'https://i.postimg.cc/sfSPTT9C/DA20.png'],
  [21, '她摸了猫', '猫让她摸了。', 'https://i.postimg.cc/m2sYJ78f/DA21.png'],
  [22, '一起逛超市', '推着购物车，像过日子的人。', 'https://i.postimg.cc/qMTsS2jg/DA22.png'],
  [23, '她挑零食', '她在零食货架前犹豫了很久。', 'https://i.postimg.cc/CLsGgdQf/DA23.png'],
  [24, '帮她拿高处的东西', '她够不到，你帮她拿了。', 'https://i.postimg.cc/NjG1fY3J/DA24.png'],
  [25, '一起做家务', '擦桌子、拖地、叠衣服。', 'https://i.postimg.cc/rwySFM68/DA25.png'],
  [26, '她在你家', '她在你家待了一整天。', 'https://i.postimg.cc/wjWD1ZHN/DA26.png'],
  [27, '你在她家', '你在她家待了一整天。', 'https://i.postimg.cc/yNkccjYr/DA27.png'],
  [28, '午睡', '她在沙发上睡着了。', 'https://i.postimg.cc/25MvwW1r/DA28.png'],
  [29, '盖毯子', '你拿了一条毯子盖在她身上。', 'https://i.postimg.cc/9M99Nf9w/DA29.png'],
  [30, '看她睡颜', '睡着的时候，她看起来和小时候一样。', 'https://i.postimg.cc/WzPZRPm7/DA30.png'],
  [31, '口水', '她睡觉流口水了。你没告诉她。', 'https://i.postimg.cc/wTgN0gj9/DA31.png'],
  [32, '接她电话', '半夜她打来电话，就聊了几句。', 'https://i.postimg.cc/zX8h08Gf/DA32.png'],
  [33, '语音消息', '她发了一段很长的语音，然后撤回了。', 'https://i.postimg.cc/DwzX36s7/DA33.png'],
  [34, '已读不回', '你发了消息，她半小时后才回。', 'https://i.postimg.cc/wjBmY2JB/DA34.png'],
  [35, '秒回', '你发了消息，她秒回了。', 'https://i.postimg.cc/JhfDJW2g/DA35.png'],
  [36, '偷拍', '她偷偷拍了你的照片。', 'https://i.postimg.cc/k4WVvpr2/DA36.png'],
  [37, '被偷拍', '你偷偷拍了她的照片。', 'https://i.postimg.cc/T1GK7JG0/DA37.png'],
  [38, '帮她拍照', '"帮我拍一张。"', 'https://i.postimg.cc/kGcBkRgR/DA38.png'],
  [39, '合照', '两个人的脸挤在一个画面里。', 'https://i.postimg.cc/9XtR4KYc/DA39.png'],
  [40, '自拍', '她举着手机，你在旁边被强行入镜。', 'https://i.postimg.cc/PrXL1ySb/DA40.png'],
  [41, '视频通话', '明明住对门，但还是视频通话了。', 'https://i.postimg.cc/52j6R0dt/DA41.png'],
  [42, '一起吹风', '站在阳台上，什么都不做，就吹风。', 'https://i.postimg.cc/JhktR2zS/DA42.png'],
  [43, '一起看夕阳', '"今天的夕阳好看。"', 'https://i.postimg.cc/Hx1nn9Jw/DA43.png'],
  [44, '一起看星星', '躺在地上/坐在天台上看星星。', 'https://i.postimg.cc/Wz246p6B/DA44.png'],
  [45, '一起发呆', '两个人都没说话，但不尴尬。', 'https://i.postimg.cc/MZDHZRqL/DA45.png'],
  [46, '她唱歌', '她小声哼了一首歌。', 'https://i.postimg.cc/G3Qt3Ybs/DA46.png'],
  [47, '教她做饭', '"你来切菜，我来炒。"', 'https://i.postimg.cc/vH2mfs10/DA47.png'],
  [48, '她切到手了', '只是一个小口子，她让你别大惊小怪。', 'https://i.postimg.cc/L8q8VbLf/DA48.png'],
  [49, '贴创可贴', '你给她贴了创可贴。', 'https://i.postimg.cc/Hkfsv99h/DA49.png'],
  [50, '一起画画', '她画你，你画她，然后对比。', 'https://i.postimg.cc/G2R3d3Np/DA50.png'],
  [51, '你画得太丑了', '"这是我？？"', 'https://i.postimg.cc/wvkqv88X/DA51.png'],
  [52, '折纸', '她教你折纸鹤。', 'https://i.postimg.cc/5yNxQ7f4/DA52.png'],
  [53, '一千只纸鹤', '"传说折一千只纸鹤可以许愿。"', 'https://i.postimg.cc/xjtjV2PV/DA53.png'],
  [54, '下棋', '棋类游戏，她出乎意料地厉害。', 'https://i.postimg.cc/MKH6WFs1/DA54.png'],
  [55, '一起看下雨', '窗边，听雨声。', 'https://i.postimg.cc/Wby2twKx/DA55.png'],
  [56, '她打喷嚏', '很小声，像猫叫。', 'https://i.postimg.cc/yYGVWytW/DA56.png'],
  [57, '给她外套', '风大了，你把外套给她。', 'https://i.postimg.cc/GpwdxhbQ/DA57.png'],
  [58, '共用一把伞', '只有一把伞，两个人挤在下面。', 'https://i.postimg.cc/fbcZ2nLD/DA58.png'],
  [59, '帮她吹头发', '洗完头发，你帮她吹。', 'https://i.postimg.cc/HxTmFZcy/DA59.png'],
  [60, '帮她扎头发', '"帮我扎一下。"你笨手笨脚地扎了。', 'https://i.postimg.cc/50pJJB8c/DA60.png'],
  [61, '一起看日历', '翻日历，数还有多少天。', 'https://i.postimg.cc/ydnKKm0K/DA61.png'],
  [62, '存钱罐', '她拿出小时候两个人的存钱罐。', 'https://i.postimg.cc/zBpNNCTY/DA62.png'],
  [63, '一起浇花', '阳台上有一盆她养的花。', 'https://i.postimg.cc/0jQsyzCb/DA63.png'],
  [64, '遇见邻居', '邻居说"你们又在一起了啊"。', 'https://i.postimg.cc/HsFgTscR/DA64.png'],
  [65, '她赖床', '"再五分钟......"', 'https://i.postimg.cc/MKnwkjHq/DA65.png'],
  [66, '给她买东西', '路过的时候看到她会喜欢的东西，买了。', 'https://i.postimg.cc/c4vWq8CN/DA66.png'],
  [67, '她给你买东西', '她递过来的时候说"随便买的"。', 'https://i.postimg.cc/cLYNCyfC/DA67.png'],
  [68, '互相剥水果', '你剥橘子给她，她剥葡萄给你。', 'https://i.postimg.cc/k5mPt1yc/DA68.png'],
  [69, '一起收拾房间', '翻出好多小时候的东西。', 'https://i.postimg.cc/HLg17ZtR/DA69.png'],
  [70, '旧日记', '在角落找到她小时候的日记本。', 'https://i.postimg.cc/vmtF7rqb/DA70.png'],
  [71, '她抢走了', '"不许看！！"', 'https://i.postimg.cc/VNWQ9qG9/DA71.png'],
  [72, '一起去便利店', '夜里十一点，两个人穿着拖鞋出门。', 'https://i.postimg.cc/1tRxv82w/DA72.png'],
  [73, '吃同一个冰淇淋', '她咬了一口，递给你。', 'https://i.postimg.cc/cH1qFv2k/DA73.png'],
  [74, '给她系鞋带', '她的鞋带松了。', 'https://i.postimg.cc/XJNMsrtM/DA74.png'],
  [75, '一起骑车', '你骑车，她坐后面。', 'https://i.postimg.cc/7hbFypxP/DA75.png'],
  [76, '她抓你的衣服', '坐后面的时候，手抓着你的衣角。', 'https://i.postimg.cc/PJNgkBt5/DA76.png'],
  [77, '一起喝奶茶', '两杯奶茶，她选的都是微糖。', 'https://i.postimg.cc/J0tfW91k/DA77.png'],
  [78, '用同一根吸管', '"你尝尝我的。"你喝了她那杯。', 'https://i.postimg.cc/90SvXJMt/DA78.png'],
  [79, '打电话不说话', '接通了但两个人都沉默，听着对方的呼吸。', 'https://i.postimg.cc/VvT3sDvc/DA79.png'],
  [80, '日常的奇迹', '所有普通的日子，回头看全是奇迹。', 'https://i.postimg.cc/QNyLqxbV/DA80.png'],
];

const WI_DATA: RawEntry[] = [
  [1, '海的约定', '"我想去看一次真正的日出。"', 'https://i.postimg.cc/fLbzJqzZ/WI1.png'],
  [2, '出发', '背着包，天还没亮就出发了。', 'https://i.postimg.cc/ZRqbCsT1/WI2.png'],
  [3, '等待', '天边一点一点亮起来。', 'https://i.postimg.cc/xCdfcpfS/WI3.png'],
  [4, '第一缕光', '太阳从地平线冒出来的那一刻。', 'https://i.postimg.cc/ydN1kp1s/WI4.png'],
  [5, '她哭了', '日出的光照在她脸上，她流泪了。', 'https://i.postimg.cc/vBSQ97Tg/WI5.png'],
  [6, '日出完成', '清单上划掉了第一条。', 'https://i.postimg.cc/0QH8mGjH/WI6.png'],
  [7, '海边的灯', '"我想在海边放一盏孔明灯。"', 'https://i.postimg.cc/90RcB4ws/WI7.png'],
  [8, '点火', '灯笼亮了，暖黄色的光。', 'https://i.postimg.cc/8c2NX1hS/WI8.png'],
  [9, '放手', '她松开手，灯飘向天空。', 'https://i.postimg.cc/gjCmtYvX/WI9.png'],
  [10, '她许了愿', '"我许了一个愿望。"灯越飘越高。', 'https://i.postimg.cc/qBSJvGWF/WI10.png'],
  [11, '灯消失了', '灯变成天上的一颗星。', 'https://i.postimg.cc/CMXhx4WY/WI11.png'],
  [12, '摩天轮', '"我想坐一次摩天轮。"', 'https://i.postimg.cc/hPmSzdBj/WI12.png'],
  [13, '排队', '排了好长的队。', 'https://i.postimg.cc/CL8FBqg4/WI13.png'],
  [14, '最高点', '在摩天轮最高点，整个城市在脚下。', 'https://i.postimg.cc/dVKJ8Vs9/WI14.png'],
  [15, '她闭上了眼', '她在最高点闭上了眼睛。', 'https://i.postimg.cc/DwK7qwvp/WI15.png'],
  [16, '美食街', '"我想吃遍一整条美食街！"', 'https://i.postimg.cc/P5kdm5Xg/WI16.png'],
  [17, '第一家', '烤串的香味。', 'https://i.postimg.cc/htbcMRhq/WI17.png'],
  [18, '吃不下了', '"我......还能吃。"', 'https://i.postimg.cc/Dwdn53mw/WI18.png'],
  [19, '最后一家', '她真的吃完了整条街。', 'https://i.postimg.cc/FKrmBCJK/WI19.png'],
  [20, '合照', '"我想拍一张合照，然后洗出来。"', 'https://i.postimg.cc/zfz5c2Rp/WI20.png'],
  [21, '拍了', '在照相馆拍了一张正式的合照。', 'https://i.postimg.cc/VNK1Q9j7/WI21.png'],
  [22, '洗出来了', '照片洗出来了，她看了很久。', 'https://i.postimg.cc/9fLV5PGv/WI22.png'],
  [23, '图书馆', '"我想在图书馆待一整天。"', 'https://i.postimg.cc/SKgqFL6Q/WI23.png'],
  [24, '她找到了', '她找到了一本一直想看的书。', 'https://i.postimg.cc/V65wYSgz/WI24.png'],
  [25, '一整天', '从开门到闭馆。', 'https://i.postimg.cc/85sG1F4c/WI25.png'],
  [26, '闭馆了', '"已经闭馆了？"', 'https://i.postimg.cc/nz5JMHSX/WI26.png'],
  [27, '露天电影', '"我想看一场露天电影。"', 'https://i.postimg.cc/G2NC9cgk/WI27.png'],
  [28, '大银幕', '银幕亮了，她的眼睛也亮了。', 'https://i.postimg.cc/gjZPZf1g/WI28.png'],
  [29, '看哭了', '电影很感人，她偷偷擦眼泪。', 'https://i.postimg.cc/prFtFggN/WI29.png'],
  [30, '手写信', '"我想收到你手写的信。"', 'https://i.postimg.cc/d3yKyzzD/WI30.png'],
  [31, '读信', '她一个字一个字地读，读了很久。', 'https://i.postimg.cc/3WQQCtTw/WI31.png'],
  [32, '信的眼泪', '信纸上多了几个水渍。', 'https://i.postimg.cc/V5PPBK8R/WI32.png'],
  [33, '淋雨', '"下雨了——我们不打伞好不好？"', 'https://i.postimg.cc/nVjs2MxQ/WI33.png'],
  [34, '冲进雨里', '她拉着你跑进雨中。', 'https://i.postimg.cc/kM02p9MT/WI34.png'],
  [35, '雨里的笑', '头发贴着脸，衣服全湿了，她在笑。', 'https://i.postimg.cc/65C8sSTH/WI35.png'],
  [36, '雨中的她', '雨水顺着她的黑发流下来，像一幅画。', 'https://i.postimg.cc/W1jhsnkh/WI36.png'],
  [37, '回去感冒了', '"值得。"她裹着毯子打了个喷嚏。', 'https://i.postimg.cc/Hk2jnywr/WI37.png'],
  [38, '第十个', '"最后一个愿望，到时候再告诉你。"', 'https://i.postimg.cc/SxrjRM65/WI38.png'],
  [39, '什么时候说', '你问了很多次，她都笑着摇头。', 'https://i.postimg.cc/432dbRFT/WI39.png'],
  [40, '时间到了', '她终于要说了。', 'https://i.postimg.cc/G2BpXgZj/WI40.png'],
  [41, '最后的愿望', '"......"', 'https://i.postimg.cc/4drxqbgL/WI41.png'],
  [42, '第一个愿望完成', '清单上划掉了第一条。', 'https://i.postimg.cc/V63kpBws/WI42.png'],
  [43, '半数完成', '清单完成了一半。', 'https://i.postimg.cc/2yhSDbjb/WI43.png'],
  [44, '只剩最后一个', '清单上只剩第十个了。', 'https://i.postimg.cc/BZK6Dy5J/WI44.png'],
  [45, '全部完成', '所有愿望，全部完成。', 'https://i.postimg.cc/Nfv0x4b6/WI45.png'],
  [46, '来不及完成', '有些愿望......来不及了。', 'https://i.postimg.cc/VL9kZCHV/WI46.png'],
  [47, '她画的清单', '愿望清单原来是她手绘的，配了小插画。', 'https://i.postimg.cc/FH9sMHMY/WI47.png'],
  [48, '清单背面', '清单的背面写了什么，被涂掉了。', 'https://i.postimg.cc/Gmqhd1R7/WI48.png'],
  [49, '第十一个', '你在她的画本里发现了被撕掉的第十一条。', 'https://i.postimg.cc/N0FG0Pfg/WI49.png'],
];

const LO_DATA: RawEntry[] = [
  [1, '第一次碰手', '手指无意间碰在一起，两个人都没动。', 'https://i.postimg.cc/PfzgBQTZ/LO1.png'],
  [2, '第一次牵手', '你主动握住了她的手。', 'https://i.postimg.cc/dQmbzjwj/LO2.png'],
  [3, '她牵你的手', '她先伸出手来。', 'https://i.postimg.cc/mZNv0yB3/LO3.png'],
  [4, '十指相扣', '手指一根一根嵌进去。', 'https://i.postimg.cc/G3JWZxdJ/LO4.png'],
  [5, '不松手', '要分开的时候，她没有松手。', 'https://i.postimg.cc/SNSBqYxw/LO5.png'],
  [6, '第一次拥抱', '你抱住了她。', 'https://i.postimg.cc/zXx9fDLL/LO6.png'],
  [7, '她抱你', '她突然从后面抱住你。', 'https://i.postimg.cc/DyxtzfWd/LO7.png'],
  [8, '很紧的拥抱', '她抱得很紧，像要把你嵌进身体里。', 'https://i.postimg.cc/JztSHwJp/LO8.png'],
  [9, '不放开', '"再抱一会儿。"', 'https://i.postimg.cc/y85tFfX5/LO9.png'],
  [10, '摸头', '你伸手摸了她的头。', 'https://i.postimg.cc/Ls17vzx6/LO10.png'],
  [11, '她摸你的头', '她踮起脚尖摸了你的头。', 'https://i.postimg.cc/fb9F5x8f/LO11.png'],
  [12, '理头发', '你帮她把吹到脸上的头发拨开。', 'https://i.postimg.cc/bJf55s5T/LO12.png'],
  [13, '擦眼泪', '你用手指擦掉她脸上的泪。', 'https://i.postimg.cc/d1cffLff/LO13.png'],
  [14, '捏脸', '你捏了她的脸。"干嘛啊！"', 'https://i.postimg.cc/W3cyyhKj/LO14.png'],
  [15, '靠肩膀', '她把头靠在你的肩膀上。', 'https://i.postimg.cc/wv5rY98T/LO15.png'],
  [16, '膝枕', '她躺在你的腿上。', 'https://i.postimg.cc/SsLPbmF8/LO16.png'],
  [17, '背靠背', '坐在地上背靠着背。', 'https://i.postimg.cc/rs8P87MG/LO17.png'],
  [18, '公主抱', '你把她抱了起来。', 'https://i.postimg.cc/XqQDXxvn/LO18.png'],
  [19, '她很轻', '她轻得让你心疼。', 'https://i.postimg.cc/nVkWdVGk/LO19.png'],
  [20, '额头相触', '两个人的额头贴在一起。', 'https://i.postimg.cc/MZDLsZmL/LO20.png'],
  [21, '脸颊之吻', '你亲了她的脸颊。', 'https://i.postimg.cc/jdSFBV8R/LO21.png'],
  [22, '她亲你脸颊', '她突然亲了你一下就跑了。', 'https://i.postimg.cc/rFwP76hR/LO22.png'],
  [23, '额头之吻', '你亲了她的额头。', 'https://i.postimg.cc/NfCzcNVH/LO23.png'],
  [24, '手背之吻', '你吻了她的手背。', 'https://i.postimg.cc/5NKRVPGn/LO24.png'],
  [25, '第一次接吻', '嘴唇碰在一起。世界安静了。', 'https://i.postimg.cc/CxZ6LGTm/LO25.png'],
  [26, '她的嘴唇很软', '比你想象的还要柔软。', 'https://i.postimg.cc/YC4yq6BB/LO26.png'],
  [27, '她的嘴唇很冷', '比你想象的还要冰凉。', 'https://i.postimg.cc/t4Lv1s9F/LO27.png'],
  [28, '她哭着吻你', '她一边流泪一边吻上来。', 'https://i.postimg.cc/BvHY2Jv8/LO28.png'],
  [29, '分开后她笑了', '嘴唇分开，她笑了。', 'https://i.postimg.cc/52ZKHXfq/LO29.png'],
  [30, '再一次', '"......再一次。"', 'https://i.postimg.cc/d0rHGJ04/LO30.png'],
  [31, '心跳加速', '你突然意识到自己的心跳很快。', 'https://i.postimg.cc/xCQsRBk6/LO31.png'],
  [32, '她的心跳', '你的手贴在她胸口，感觉到不规则的跳动。', 'https://i.postimg.cc/RFmPR26x/LO32.png'],
  [33, '说不出口', '有句话在嘴边，但说不出来。', 'https://i.postimg.cc/26x0XThk/LO33.png'],
  [34, '她也说不出口', '她看着你，张了张嘴，又低下了头。', 'https://i.postimg.cc/gJKgB486/LO34.png'],
  [35, '我喜欢你', '你对她说了。', 'https://i.postimg.cc/ZnKwk3x3/LO35.png'],
  [36, '她的回答', '她的回答不是"我也是"，是眼泪。', 'https://i.postimg.cc/L56xdf30/LO36.png'],
  [37, '她的告白', '"我也......我早就......"', 'https://i.postimg.cc/BZMhTYJp/LO37.png'],
  [38, '迟到的告白', '如果她早点说就好了。', 'https://i.postimg.cc/NGpN6JQx/LO38.png'],
  [39, '在一起', '"我们在一起吧。"', 'https://i.postimg.cc/Pf26W3dK/LO39.png'],
  [40, '男朋友', '她第一次叫你"男朋友"。', 'https://i.postimg.cc/ZYVf87JQ/LO40.png'],
  [41, '情侣装', '穿了同款T恤出门。', 'https://i.postimg.cc/L4NytCH4/LO41.png'],
  [42, '情侣头像', '她把头像换成了两个人的合照。', 'https://i.postimg.cc/m2km8YDs/LO42.png'],
  [43, '备注', '她把你的备注改了。', 'https://i.postimg.cc/Yq0db69N/LO43.png'],
  [44, '晚安吻', '分开时在门口亲了一下。', 'https://i.postimg.cc/Fs6DqYdn/LO44.png'],
  [45, '早安吻', '开门看到她，先亲了一下。', 'https://i.postimg.cc/mgF8GTCX/LO45.png'],
  [46, '她在你怀里', '你从后面环住她。', 'https://i.postimg.cc/3xDnH32H/LO46.png'],
  [47, '你在她怀里', '她难得地把你揽进怀里。', 'https://i.postimg.cc/s2dKjbJ3/LO47.png'],
  [48, '睡着了不松手', '睡着了还握着你的手。', 'https://i.postimg.cc/yN4n12TZ/LO48.png'],
  [49, '一起睡', '第一次在同一张床上入睡。', 'https://i.postimg.cc/R07dNGPd/LO49.png'],
  [50, '她的体温', '她的体温比你想象的低。', 'https://i.postimg.cc/4dX5ttqR/LO50.png'],
  [51, '嫉妒', '她看到你和别人聊天，不高兴了。', 'https://i.postimg.cc/3R3BppVD/LO51.png'],
  [52, '你嫉妒了', '有人看她，你不高兴了。', 'https://i.postimg.cc/50pmmyWm/LO52.png'],
  [53, '吵架', '第一次真正意义上吵架了。', 'https://i.postimg.cc/L5X3QSm3/LO53.png'],
  [54, '和好', '吵完架，她站在你门口。', 'https://i.postimg.cc/2yKFPt6k/LO54.png'],
  [55, '道歉', '"对不起。"', 'https://i.postimg.cc/QCykRztM/LO55.png'],
  [56, '不要走', '"不要走。留下来。"', 'https://i.postimg.cc/c19mgvck/LO56.png'],
  [57, '约会', '第一次正式的约会。', 'https://i.postimg.cc/y6QPgDPd/LO57.png'],
  [58, '礼物', '你送了她一个礼物。', 'https://i.postimg.cc/vHCthCkL/LO58.png'],
  [59, '她的礼物', '她也准备了一个给你。', 'https://i.postimg.cc/ZKXxHX2f/LO59.png'],
  [60, '对戒', '两枚简单的戒指。', 'https://i.postimg.cc/qvnX5jdN/LO60.png'],
  [61, '她的秘密', '她有什么事瞒着你。', 'https://i.postimg.cc/cJSMywsn/LO61.png'],
  [62, '追问', '你追问了，她沉默了。', 'https://i.postimg.cc/rpNG8smQ/LO62.png'],
  [63, '不再追问', '你决定不再问了。', 'https://i.postimg.cc/26jQ3YLR/LO63.png'],
  [64, '她哭了', '她在你面前哭了。忍不住的那种。', 'https://i.postimg.cc/tTR37bng/LO64.png'],
  [65, '接住她', '你什么都没说，只是抱住她。', 'https://i.postimg.cc/bJ6Qt51T/LO65.png'],
  [66, '你也哭了', '你也忍不住了。', 'https://i.postimg.cc/tJYFtz5Q/LO66.png'],
  [67, '一起哭', '两个人抱在一起哭。', 'https://i.postimg.cc/5yTLPF7y/LO67.png'],
  [68, '哭完了', '哭完之后，她笑了。', 'https://i.postimg.cc/sfNYftjM/LO68.png'],
  [69, '你是我的', '"你是我的。"', 'https://i.postimg.cc/pLNKzz5S/LO69.png'],
  [70, '我是你的', '"我是你的。"', 'https://i.postimg.cc/fRxmKyxQ/LO70.png'],
  [71, '永远', '她说"永远"的时候，声音在发抖。', 'https://i.postimg.cc/JzbZq0bG/LO71.png'],
  [72, '别说永远', '"不要说永远......"', 'https://i.postimg.cc/k5q8hCcS/LO72.png'],
  [73, '如果有来世', '"如果有来世......你还愿意认识我吗？"', 'https://i.postimg.cc/ZRqN4LXK/LO73.png'],
  [74, '当然', '"当然。每一世都会找到你。"', 'https://i.postimg.cc/pTdjRB3T/LO74.png'],
  [75, '她笑了', '她笑着哭了。或者哭着笑了。', 'https://i.postimg.cc/1tzFsKb3/LO75.png'],
  [76, '第一次留下', '那天晚上，她没有回去。', 'https://i.postimg.cc/TwHDwDX9/LO76.png'],
  [77, '在你身边醒来', '早上睁开眼，她就在旁边。', 'https://i.postimg.cc/631v3vXw/LO77.png'],
  [78, '她的背影', '她坐在床边，长发垂下来。', 'https://i.postimg.cc/x8Jbb1fX/LO78.png'],
  [79, '肩膀上的吻', '你亲了她裸露的肩膀。', 'https://i.postimg.cc/x8wNGV8K/LO79.png'],
  [80, '锁骨', '她的锁骨很明显。', 'https://i.postimg.cc/28WZky9h/LO80.png'],
  [81, '第一夜', '两个人，完完整整地在一起了。', 'https://i.postimg.cc/PrDwXJFG/LO81.png'],
  [82, '很温柔', '你很温柔。她也是。', 'https://i.postimg.cc/0yqJbvLs/LO82.png'],
  [83, '她的眼泪', '做的时候她哭了。不是痛，是太满了。', 'https://i.postimg.cc/cLMt3jSs/LO83.png'],
  [84, '不要松手', '"不要松手......"', 'https://i.postimg.cc/g2qLh5WS/LO84.png'],
  [85, '事后', '她蜷在你怀里，像一只虾。', 'https://i.postimg.cc/43WKL9yq/LO85.png'],
  [86, '心跳', '两个人的心跳声重叠在一起。', 'https://i.postimg.cc/7LKCs2bf/LO86.png'],
  [87, '她睡着了', '做完她睡着了，脸上还有泪痕。', 'https://i.postimg.cc/MTXnhpjH/LO87.png'],
  [88, '你没睡', '你看了她一整夜。', 'https://i.postimg.cc/LXhJr8ZP/LO88.png'],
  [89, '吻痕', '她脖子上有你留的印子。', 'https://i.postimg.cc/gJ5xdbv4/LO89.png'],
  [90, '她的吻痕', '你肩膀上也有。', 'https://i.postimg.cc/XJhr36fj/LO90.png'],
  [91, '我会记住', '"我会记住你说的每一句话。"', 'https://i.postimg.cc/wMm7j42h/LO91.png'],
  [92, '给她的承诺', '你对她许了一个承诺。', 'https://i.postimg.cc/c6G6g7km/LO92.png'],
  [93, '她的承诺', '她也许了一个。', 'https://i.postimg.cc/gcntG99H/LO93.png'],
  [94, '别忘了我', '"别忘了我。"', 'https://i.postimg.cc/J7GYRwwc/LO94.png'],
  [95, '怎么可能忘', '"怎么可能。"', 'https://i.postimg.cc/9Xrgc33n/LO95.png'],
  [96, '你要好好活', '"你要好好活着。"', 'https://i.postimg.cc/fWp2LHDZ/LO96.png'],
  [97, '不公平', '"凭什么你能说这种话。"', 'https://i.postimg.cc/HsMS7Qkk/LO97.png'],
  [98, '对不起', '"对不起，让你遇到了我这样的人。"', 'https://i.postimg.cc/QdrfgHFq/LO98.png'],
  [99, '谢谢你', '"谢谢你，出现在我的人生里。"', 'https://i.postimg.cc/6pNMVy8S/LO99.png'],
  [100, '我爱你', '"我爱你。"没有但是。', 'https://i.postimg.cc/0ydcVPm9/LO100.png'],
];

const TR_DATA: RawEntry[] = [
  [1, '出门吧', '"今天出去走走吧。"', 'https://i.postimg.cc/6qX8bJCQ/TR1.png'],
  [2, '背包客', '背上双肩包，像真正的旅行者。', 'https://i.postimg.cc/L5pJQKjX/TR2.png'],
  [3, '公交车', '坐公交车去远一点的地方。', 'https://i.postimg.cc/HngrvDb8/TR3.png'],
  [4, '她靠窗', '她坐靠窗的位置，看着外面。', 'https://i.postimg.cc/br9sKCRR/TR4.png'],
  [5, '地铁', '拥挤的地铁里，她贴着你。', 'https://i.postimg.cc/gcVXXjPW/TR5.png'],
  [6, '走丢了', '在陌生的地方走散了五分钟。', 'https://i.postimg.cc/RC766hzK/TR6.png'],
  [7, '找到了', '你找到她的时候，她装作没有害怕。', 'https://i.postimg.cc/qMpt8rkw/TR7.png'],
  [8, '古镇', '去了一个古色古香的小镇。', 'https://i.postimg.cc/15M8BdtT/TR8.png'],
  [9, '桥', '一座旧桥上，河水在下面流。', 'https://i.postimg.cc/y8dkbT3s/TR9.png'],
  [10, '河边', '两个人坐在河边，把脚伸进水里。', 'https://i.postimg.cc/3xRdcZ0w/TR10.png'],
  [11, '山', '爬了一座不高的山。', 'https://i.postimg.cc/t4MYQVF2/TR11.png'],
  [12, '她走不动了', '她在半山腰说"我没事"，但在喘。', 'https://i.postimg.cc/rpRz8FJV/TR12.png'],
  [13, '背着她', '你蹲下来说"上来"。', 'https://i.postimg.cc/HxGnjDZn/TR13.png'],
  [14, '山顶', '站在山顶上，风很大。', 'https://i.postimg.cc/ydFdZQtG/TR14.png'],
  [15, '大喊', '她在山顶大喊了一声。', 'https://i.postimg.cc/Rh40Q1zS/TR15.png'],
  [16, '寺庙', '去了一座寺庙，她很认真地拜了。', 'https://i.postimg.cc/J0xzTy1D/TR16.png'],
  [17, '她许了什么愿', '"说了就不灵了。"', 'https://i.postimg.cc/tJk4r1Xc/TR17.png'],
  [18, '拍立得', '在景点的拍立得机器前拍了一张。', 'https://i.postimg.cc/fTWLVvK7/TR18.png'],
  [19, '旅馆', '住了一家很旧但很干净的小旅馆。', 'https://i.postimg.cc/28j61xw4/TR19.png'],
  [20, '两张床', '明明两张床，半夜她爬过来了。', 'https://i.postimg.cc/J47nsQqf/TR20.png'],
  [21, '民宿', '住在一个能看到星星的民宿。', 'https://i.postimg.cc/Qx6M1WYr/TR21.png'],
  [22, '路边摊', '路边的烤红薯，两个人分一个。', 'https://i.postimg.cc/28H5hB93/TR22.png'],
  [23, '迷路', '"你确定是这条路？"', 'https://i.postimg.cc/kgBgcXL8/TR23.png'],
  [24, '问路', '她去问路了。', 'https://i.postimg.cc/0ybyf2hH/TR24.png'],
  [25, '博物馆', '安安静静地逛了一个博物馆。', 'https://i.postimg.cc/bwWNFfhc/TR25.png'],
  [26, '水族馆', '蓝色的光打在她脸上。', 'https://i.postimg.cc/TPb2zNdf/TR26.png'],
  [27, '她喜欢水母', '"水母好自由......"', 'https://i.postimg.cc/mDGZB3kc/TR27.png'],
  [28, '游乐园', '去了一次游乐园。', 'https://i.postimg.cc/6qX8bJCy/TE28.png'],
  [29, '摩天轮', '在摩天轮最高点。', 'https://i.postimg.cc/XJ0N4Kqz/TR29.png'],
  [30, '旋转木马', '她坐在木马上。', 'https://i.postimg.cc/4dbfdKHr/TR30.png'],
  [31, '她害怕过山车', '"我才不怕！......你拉着我的手。"', 'https://i.postimg.cc/4dbfdKhN/TR31.png'],
  [32, '夹娃娃', '你花了很多钱夹了一个给她。', 'https://i.postimg.cc/rsV8t8Sy/TR32.png'],
  [33, '花海', '走进一片花海，她在花里转圈。', 'https://i.postimg.cc/90mWqWGd/TR33.png'],
  [34, '花冠', '你给她编了一个花冠。', 'https://i.postimg.cc/SRgm6wrd/TR34.png'],
  [35, '她戴上了', '你说"很好看"。', 'https://i.postimg.cc/nV2VfDJQ/TR35.png'],
  [36, '图书馆', '去了一家很大的图书馆。', 'https://i.postimg.cc/jqcqY7bw/TR36.png'],
  [37, '她找到了一本书', '一本一直想看的旅行文学。', 'https://i.postimg.cc/Y2R2BWHP/TR37.png'],
  [38, '咖啡馆', '窗边的位置，两杯咖啡。', 'https://i.postimg.cc/65QWWp6N/TR38.png'],
  [39, '她不喝咖啡', '她点了热巧克力。', 'https://i.postimg.cc/KvsZRh4P/TR39.png'],
  [40, '落日海滩', '在海滩上看日落。', 'https://i.postimg.cc/mgvBy3Qq/TR40.png'],
  [41, '沿海公路', '窗外是无尽的海岸线。', 'https://i.postimg.cc/VkxmW9qf/TR41.png'],
  [42, '灯塔', '"灯塔在等船回来。"', 'https://i.postimg.cc/g2CmHyVr/TR42.png'],
  [43, '天文台', '她用望远镜看月亮。', 'https://i.postimg.cc/6QCwj7cy/TR43.png'],
  [44, '她说了一句话', '让你永远记住的话。', 'https://i.postimg.cc/N0RYJyD8/TR44.png'],
  [45, '纪念品', '她挑了一个纪念品。', 'https://i.postimg.cc/FK0mWfpD/TR45.png'],
  [46, '给你的纪念品', '她偷偷买了相同的给你。', 'https://i.postimg.cc/C1Y0WFrD/TR46.png'],
  [47, '照片墙', '把旅行照片贴在墙上。', 'https://i.postimg.cc/B6s3dq7h/TR47.png'],
  [48, '她的旅行地图', '标记了去过的地方。', 'https://i.postimg.cc/9MV2vWNV/TR48.png'],
  [49, '最远的地方', '两个人一起去过的最远的地方。', 'https://i.postimg.cc/630KKDDJ/TR49.png'],
  [50, '回家', '"回家吧。"', 'https://i.postimg.cc/7hZkZKkZ/TR50.png'],
];

const ME_DATA: RawEntry[] = [
  [1, '小时候的照片', '翻出了小时候的照片。', 'https://i.postimg.cc/4dF8pPcb/ME1.png'],
  [2, '她小时候的样子', '扎着马尾辫，笑得张牙舞爪。', 'https://i.postimg.cc/85nyL4vZ/ME2.png'],
  [3, '你小时候的样子', '"你小时候真的好丑哈哈。"', 'https://i.postimg.cc/Y0GdRFNV/ME3.png'],
  [4, '游泳', '"我小时候可会游泳了......"', 'https://i.postimg.cc/VvrKgt9p/ME4.png'],
  [5, '不能游泳了', '说完这句话，她安静了。', 'https://i.postimg.cc/6qkYmQY6/ME5.png'],
  [6, '过家家', '"你还记得我们小时候过家家吗？"', 'https://i.postimg.cc/FzMDBKDk/ME06.png'],
  [7, '你当爸爸', '"你当爸爸我当妈妈。"', 'https://i.postimg.cc/HWFmg4NX/ME7.png'],
  [8, '沙子菜', '"你做的沙子菜我全部都假装吃了。"', 'https://i.postimg.cc/HWFmg4NQ/ME8.png'],
  [9, '第一次上学', '"第一天上学你哭了。"', 'https://i.postimg.cc/7Pj4kMRS/ME9.png'],
  [10, '跌倒', '"你跌倒的时候我帮你吹伤口。"', 'https://i.postimg.cc/CLDgLny9/ME10.png'],
  [11, '一起做作业', '"你的数学作业全是我帮你写的。"', 'https://i.postimg.cc/NjkvRhjb/ME11.png'],
  [12, '捉迷藏', '"你每次都藏衣柜。"', 'https://i.postimg.cc/YCzBQcCd/ME12.png'],
  [13, '童年的约定', '"你答应过带我去看海的。"', 'https://i.postimg.cc/y8yC0q8T/ME13.png'],
  [14, '交换了什么', '小时候交换的东西，她还留着。', 'https://i.postimg.cc/R0C5RPWd/ME14.png'],
  [15, '身高线', '门框上刻的身高线还在。', 'https://i.postimg.cc/wBx8VWtH/ME15.png'],
  [16, '她比你高的时候', '"有一年我比你高了两厘米！"', 'https://i.postimg.cc/9fx3NGT0/ME16.png'],
  [17, '旧玩具', '找到了两个人的旧玩具。', 'https://i.postimg.cc/g0M9BvRr/ME17.png'],
  [18, '信箱', '两个人做了一个秘密信箱。', 'https://i.postimg.cc/d1LMMLmL/ME18.png'],
  [19, '信箱里的纸条', '里面还有没取出来的纸条。', 'https://i.postimg.cc/B6XWWXcC/ME19.png'],
  [20, '纸条上写的', '"我喜欢和你玩。——小潮汐"', 'https://i.postimg.cc/V6dyydB2/ME20.png'],
  [21, '她哭了', '看到旧东西的时候，她突然哭了。', 'https://i.postimg.cc/sX8k3sTV/ME21.png'],
  [22, '生日蛋糕', '"你还记得我八岁生日蛋糕掉地上了吗？"', 'https://i.postimg.cc/rsrvm3Hw/ME22.png'],
  [23, '星星灯', '她小时候房间有一盏星星夜灯。', 'https://i.postimg.cc/Vs0yD0Nc/ME23.png'],
  [24, '还亮着', '那盏灯还亮着。', 'https://i.postimg.cc/8kf8tfCG/ME24.png'],
  [25, '她的房间', '走进她的房间，和以前不一样了。', 'https://i.postimg.cc/Df4VB4zb/ME25.png'],
  [26, '安静的房间', '房间很整洁，但缺少生活气息。', 'https://i.postimg.cc/qBPPYBtR/ME26.png'],
  [27, '书架', '她的书架上全是旅行相关的书。', 'https://i.postimg.cc/05TT356B/ME27.png'],
  [28, '画本', '她的画本摞了很多。', 'https://i.postimg.cc/CLb3VyDH/ME28.png'],
  [29, '画的变化', '越往后，画得越安静，色彩越淡。', 'https://i.postimg.cc/xTLwSrM0/ME29.png'],
  [30, '确诊那天', '她第一次告诉你确诊那天的事。', 'https://i.postimg.cc/L8Rr9y32/ME30.png'],
  [31, '为什么不说', '"你为什么不告诉我？"', 'https://i.postimg.cc/dVvzsWjk/ME31.png'],
  [32, '她的回答', '"告诉你又能怎样呢。"', 'https://i.postimg.cc/g2D1nvgD/ME32.png'],
  [33, '转学的真相', '"转学"从来都不是真的。', 'https://i.postimg.cc/dVBgL85j/ME33.png'],
  [34, '那一年', '她休学的那一年。', 'https://i.postimg.cc/DwgR8qxN/ME34.png'],
  [35, '后悔', '"我是不是应该更早发现的。"', 'https://i.postimg.cc/5t2Tv6rh/ME35.png'],
  [36, '不是你的错', '"不是你的错。"', 'https://i.postimg.cc/QMYPqjGF/ME36.png'],
  [37, '傻瓜相机', '找到了她小时候的傻瓜相机。', 'https://i.postimg.cc/W4YK7sLh/ME37.png'],
  [38, '照片还在', '里面的照片还没取出来过。', 'https://i.postimg.cc/JhYgQRV0/ME38.png'],
  [39, '最后一张', '最后一张照片，是你的侧脸。', 'https://i.postimg.cc/vm2jvGF7/ME39.png'],
  [40, '她的秘密都是你', '所有的秘密，都和你有关。', 'https://i.postimg.cc/j5W1gBtQ/ME40.png'],
];

const IL_DATA: RawEntry[] = [
  [1, '她看起来很好', '完全看不出来。', 'https://i.postimg.cc/5ysFXKFx/IL1.png'],
  [2, '小挎包', '她从不让你翻她的小挎包。', 'https://i.postimg.cc/QCfWFYWG/IL2.png'],
  [3, '定时闹钟', '她的手机每天固定时间响。', 'https://i.postimg.cc/0jVJzXJz/IL3.png'],
  [4, '偷偷吃药', '你没看到，但她去了洗手间。', 'https://i.postimg.cc/dQ6CN3N9/IL4.png'],
  [5, '没事', '"我没事。"说的次数越来越多。', 'https://i.postimg.cc/MZ5B3Hrk/IL5.png'],
  [6, '喘了一下', '爬楼梯的时候，她顿了一下。', 'https://i.postimg.cc/1RBF7XYP/IL6.png'],
  [7, '你等她', '你停下来等她。', 'https://i.postimg.cc/MKGQCwhH/IL7.png'],
  [8, '她的借口', '"昨晚没睡好。"', 'https://i.postimg.cc/vHSVMjsN/IL8.png'],
  [9, '第二次', '又一次。这次更明显了。', 'https://i.postimg.cc/kXhb9ZmZ/IL9.png'],
  [10, '你没说破', '你看到了，但你没说。', 'https://i.postimg.cc/mgzFrwZZ/IL10.png'],
  [11, '走慢一点', '你开始不自觉地放慢步速。', 'https://i.postimg.cc/BnL1vgZn/IL11.png'],
  [12, '坐下来歇歇', '"我们坐下来歇歇吧。"', 'https://i.postimg.cc/wjCRRm3y/IL12.png'],
  [13, '她的倔强', '"我可以的，不用你......"', 'https://i.postimg.cc/s25QYgZ7/IL13.png'],
  [14, '接过她的包', '你把她的包接过来背。', 'https://i.postimg.cc/zfTbCGRM/IL14.png'],
  [15, '她没拒绝', '这次她没有拒绝。', 'https://i.postimg.cc/bJTZ5Vgz/IL15.png'],
  [16, '嘴唇', '你第一次注意到她的嘴唇颜色不对。', 'https://i.postimg.cc/gJdwNbVX/IL16.png'],
  [17, '指甲', '她的指甲有点发青。', 'https://i.postimg.cc/Zn5WzPs8/IL17.png'],
  [18, '走不远了', '以前能走的路，现在走一半就要停。', 'https://i.postimg.cc/8cz7gdXH/IL18.png'],
  [19, '她开始道歉', '"对不起，又要休息了。"', 'https://i.postimg.cc/90grm4s6/IL19.png'],
  [20, '别说对不起', '"别说对不起。"', 'https://i.postimg.cc/SR1JSXw4/IL20.png'],
  [21, '药量增加', '她吃的药比以前多了。', 'https://i.postimg.cc/90grm4v7/IL21.png'],
  [22, '你看到了', '你终于看到了她吃药的样子。', 'https://i.postimg.cc/tRB1tf7m/IL22.png'],
  [23, '那是什么药', '你忍不住查了药名。', 'https://i.postimg.cc/FFTfgq7m/IL23.png'],
  [24, '搜索结果', '手机屏幕上的字，每一个都像针。', 'https://i.postimg.cc/c46vDmnc/IL24.png'],
  [25, '知道了', '你知道了。', 'https://i.postimg.cc/GhNH6yFf/IL25.png'],
  [26, '崩溃', '你在没有她的地方崩溃了。', 'https://i.postimg.cc/jS7LTSvt/IL26.png'],
  [27, '装作不知道', '你装作什么都没有。', 'https://i.postimg.cc/d0cDVcSQ/IL27.png'],
  [28, '装不下去了', '你装了几天，装不下去了。', 'https://i.postimg.cc/q7HgvHZt/IL28.png'],
  [29, '你问了', '"潮汐......你是不是......"', 'https://i.postimg.cc/hG8vJZHM/IL29.png'],
  [30, '她沉默了', '她看着你，没有说话。很久。', 'https://i.postimg.cc/9MWMyt2C/IL30.png'],
  [31, '摊牌', '她把所有事都告诉你了。', 'https://i.postimg.cc/HxBLzcW7/IL31.png'],
  [32, '多久', '"还有多久？""......不知道。"', 'https://i.postimg.cc/bJ3vgDYC/IL32.png'],
  [33, '你抱住她', '你什么话都没说，只是抱住了她。', 'https://i.postimg.cc/brrwBydC/IL33.png'],
  [34, '她说对不起', '"对不起。对不起。对不起。"', 'https://i.postimg.cc/7hhZWHfy/IL34.png'],
  [35, '走不稳了', '她走路开始不太稳了。', 'https://i.postimg.cc/90kQ367W/IL35.png'],
  [36, '你扶着她', '她的手挽在你的胳膊上。', 'https://i.postimg.cc/nrWh8yDQ/IL36.png'],
  [37, '轮椅', '你们租了一辆轮椅。', 'https://i.postimg.cc/1Xd3xkqr/IL37.png'],
  [38, '她不想坐', '"我还能走......"', 'https://i.postimg.cc/qBDRC35f/IL38.png'],
  [39, '坐下了', '最后她还是坐下了。', 'https://i.postimg.cc/J7YnBk2n/IL39.png'],
  [40, '你推着她', '你推着轮椅，她坐在里面。', 'https://i.postimg.cc/tRvTVxMV/IL40.png'],
  [41, '下肢浮肿', '她的脚踝肿了。', 'https://i.postimg.cc/Yq4SNC5y/IL41.png'],
  [42, '晕厥', '她毫无预兆地倒下了。', 'https://i.postimg.cc/yYw8LzKT/IL42.png'],
  [43, '医院', '你们去了医院。', 'https://i.postimg.cc/GhZmX1R5/IL43.png'],
  [44, '医生说', '医生说的每个字你都不想听。', 'https://i.postimg.cc/5NZ2sM1M/IL44.png'],
  [45, '她的父母', '她的父母在走廊上哭了。', 'https://i.postimg.cc/mgC2q62L/IL45.png'],
  [46, '你的承诺', '你对她父母说了什么。', 'https://i.postimg.cc/MGwK8bvM/IL46.png'],
  [47, '回家', '"带我回家。"', 'https://i.postimg.cc/d0FtKmLB/IL47.png'],
  [48, '药物清单', '你开始帮她管药。', 'https://i.postimg.cc/fbvWWt95/IL48.png'],
  [49, '闹钟换人了', '以前是她手机响，现在是你的。', 'https://i.postimg.cc/7LNPPG2R/IL49.png'],
  [50, '她变轻了', '你抱她的时候，她又轻了一些。', 'https://i.postimg.cc/LsV44YP9/IL50.png'],
  [51, '下不了床了', '她大部分时间都在床上了。', 'https://i.postimg.cc/bJNyZy0Z/IL51.png'],
  [52, '你守着她', '你搬了椅子坐在床边。', 'https://i.postimg.cc/zBtJWspR/IL52.png'],
  [53, '她的手很冷', '她的手越来越凉了。', 'https://i.postimg.cc/B6YqDrNB/IL53.png'],
  [54, '握紧', '你握紧她的手。', 'https://i.postimg.cc/nzRH7yTN/IL54.png'],
  [55, '她还在笑', '这个时候了，她还在笑。', 'https://i.postimg.cc/sxM3JT0L/IL55.png'],
  [56, '最后的力气', '她用最后的力气做了一件事。', 'https://i.postimg.cc/ZnX4s6Gq/IL56.png'],
  [57, '最后一幅画', '她画了最后一幅画。', 'https://i.postimg.cc/0jhPX7Td/IL57.png'],
  [58, '最后的话', '她说了最后的话。', 'https://i.postimg.cc/SQPSKpJB/IL58.png'],
  [59, '闭上眼睛', '她闭上了眼睛。', 'https://i.postimg.cc/h4YDGqX4/IL59.png'],
  [60, '8月31日', '她没能过完她的十九岁生日。', 'https://i.postimg.cc/054kNqz7/IL60.png'],
];

const TI_DATA: RawEntry[] = Array.from({ length: 31 }, (_, i) => {
  const d = i + 1;
  const descs: Record<number, string> = {
    1: '第一天。', 2: '第二天。', 3: '第三天。', 4: '第四天。', 5: '第五天。',
    6: '第六天。', 7: '第一周过去了。', 8: '第八天。', 9: '第九天。', 10: '第十天。',
    11: '十一天。', 12: '十二天。', 13: '十三天。', 14: '两周了。', 15: '时间过了一半了。',
    16: '十六天。', 17: '十七天。', 18: '十八天。', 19: '十九天。', 20: '只剩十一天。',
    21: '二十一天。', 22: '还剩九天。', 23: '倒计时开始了。', 24: '还剩七天。', 25: '还剩六天。',
    26: '还剩五天。', 27: '还剩四天。', 28: '还剩三天。', 29: '还剩两天。', 30: '最后一天的前夜。',
    31: '她的十九岁生日。最后一天。',
  };
  const name = d === 31 ? '8月31日 - 生日' : `8月${d}日`;
  return [d, name, descs[d], `https://i.postimg.cc/${['Gt7L1Z6z','KjvGwZpV','HnZYCfFt','hvyDqHNy','FzWrQ22m','zvtz199z','ZYVK3d0y','c1X4Yn63','QN0x5TVn','pVqX8FpN','1RJ56q4L','qMqBGvCY','vHT8vZVs','Yq02xCW9','dt3Q9Vyk','m2nLpWYc','ncWFSf41','wjs6S425','QdWXRYmm','Dwb2tp6N','wjs6S4FH','ht7SHZMS','xdD0YGF1','KYSZF7sR','YSKpkNyL','KYPmYKdR','nL4nLs6B','k5Q75Vkf','50fbQ4Vp','zBq8HzrQ','MTzqf6SN'][i]}/TI${d}.png`] as RawEntry;
});

const SP_DATA: RawEntry[] = [
  [1, '下雨了', '毫无预兆的大雨。', 'https://i.postimg.cc/8C5x27TF/SP1.png'],
  [2, '停电', '整栋楼突然停电了。', 'https://i.postimg.cc/7L6jF5q5/SP2.png'],
  [3, '蜡烛', '在蜡烛光下看着对方。', 'https://i.postimg.cc/vmBCJ4Gg/SP3.png'],
  [4, '流星', '夜空中划过一颗流星。', 'https://i.postimg.cc/MGTgCnzf/SP4.png'],
  [5, '她没许愿', '"流星太快了，来不及许。"', 'https://i.postimg.cc/hGjNkXK9/SP5.png'],
  [6, '你替她许了', '你在心里替她许了一个愿。', 'https://i.postimg.cc/TP4BfTPp/SP6.png'],
  [7, '彩虹', '雨后看到了彩虹。', 'https://i.postimg.cc/jjFBtRjD/SP7.png'],
  [8, '蒲公英', '她吹了一朵蒲公英。', 'https://i.postimg.cc/LsbG2msq/SP8.png'],
  [9, '风铃', '她挂了一只风铃在窗户上。', 'https://i.postimg.cc/jjFBtRjn/SP9.png'],
  [10, '四叶草', '她在草地上找到了四叶草。', 'https://i.postimg.cc/mr5KBTrH/SP10.png'],
  [11, '路上的流浪猫', '一只流浪猫跟着你们。', 'https://i.postimg.cc/cJbP0dJ7/SP11.png'],
  [12, '她要收养', '"我们能不能......"', 'https://i.postimg.cc/43SjsX3B/SP12.png'],
  [13, '你养了', '"我帮你养。"', 'https://i.postimg.cc/6QmFtBQ1/SP13.png'],
  [14, '猫的名字', '她给猫取了名字。', 'https://i.postimg.cc/pT54d39Z/SP14.png'],
  [15, '日记', '她每天都在写东西。', 'https://i.postimg.cc/XJBmvtZD/SP15.png'],
  [16, '给你的日记', '那本日记是写给你的。', 'https://i.postimg.cc/50QTtDHZ/SP16.png'],
  [17, '信', '她写了很多封信，藏在不同地方。', 'https://i.postimg.cc/qR6S7Whp/SP17.png'],
  [18, '最后一次出门', '她最后一次能自己走出家门。', 'https://i.postimg.cc/ZRv2qXBK/SP18.png'],
  [19, '她回头了', '她在门口回头看了一眼家。', 'https://i.postimg.cc/B6PkvRL6/SP19.png'],
  [20, '你好吗', '"我很好。"', 'https://i.postimg.cc/PJGcvKYj/SP20.png'],
  [21, '她确实很好', '因为你在。', 'https://i.postimg.cc/0jg3KZD5/SP21.png'],
  [22, '最后的夜晚', '8月30日的夜晚。', 'https://i.postimg.cc/sxF8GK7v/SP22.png'],
  [23, '不要睡', '"今晚不要睡。陪我说说话。"', 'https://i.postimg.cc/J0wgHKZN/SP23.png'],
  [24, '一整夜的话', '她说了很多。', 'https://i.postimg.cc/NF1n6Tkr/SP24.png'],
  [25, '天亮了', '天亮了。8月31日。', 'https://i.postimg.cc/D0qNrsPq/SP25.png'],
];

const OB_DATA: RawEntry[] = [
  [1, '纸鹤', '她折的纸鹤。', 'https://i.postimg.cc/qBs0XCqR/OB1.png'],
  [2, '纸星星', '一罐纸星星。', 'https://i.postimg.cc/RVvmPVJ9/OB2.png'],
  [3, '画本', '她的画本。', 'https://i.postimg.cc/15ySW5Vz/OB3.png'],
  [4, '你的画像', '她画的你。', 'https://i.postimg.cc/7Yq4BYJP/OB4.png'],
  [5, '贝壳', '海边捡的贝壳。', 'https://i.postimg.cc/MKzwsKff/OB5.png'],
  [6, '拍立得照片', '两个人的拍立得。', 'https://i.postimg.cc/CLw0vLnj/OB6.png'],
  [7, '花冠', '压干的花冠。', 'https://i.postimg.cc/m2T4d21Y/OB7.png'],
  [8, '四叶草', '她找到的四叶草。', 'https://i.postimg.cc/CLw0vLns/OB8.png'],
  [9, '戒指', '两枚对戒中的一枚。', 'https://i.postimg.cc/hPMBNWV7/OB9.png'],
  [10, '纪念品', '旅行时她挑的纪念品。', 'https://i.postimg.cc/65zXFJCd/OB10.png'],
  [11, '项链', '她的一条项链。', 'https://i.postimg.cc/xTg2BDLR/OB11.png'],
  [12, '日记本', '她写给你的日记本。', 'https://i.postimg.cc/FsG4w50D/OB12.png'],
  [13, '信件', '她写的那些信。', 'https://i.postimg.cc/ncTJNbqP/OB13.png'],
  [14, '录音', '她录的那段语音。', 'https://i.postimg.cc/QxS3vGcv/OB14.png'],
  [15, '视频', '她录的那段视频。', 'https://i.postimg.cc/fy9VBWVd/OB15.png'],
  [16, '存钱罐', '小时候的存钱罐。', 'https://i.postimg.cc/ZKjSXtrz/OB16.png'],
  [17, '风铃', '她挂的风铃。', 'https://i.postimg.cc/sgXrr6JL/OB17.png'],
  [18, '她的浴衣', '夏日祭时她穿的浴衣。', 'https://i.postimg.cc/4xdggL1q/OB18.png'],
  [19, '苹果糖棍子', '她洗干净留着的。', 'https://i.postimg.cc/HkxggZ2C/OB19.png'],
  [20, '创可贴', '你给她贴的那个创可贴。', 'https://i.postimg.cc/13tQQCH3/OB20.png'],
  [21, '药盒', '她的药盒。空了。', 'https://i.postimg.cc/dV1YYHB3/OB21.png'],
  [22, '注射泵', '她的注射泵。', 'https://i.postimg.cc/t4TjjS5T/OB22.png'],
  [23, '手写信', '你写给她的那封信。', 'https://i.postimg.cc/wjvppfV1/OB23.png'],
  [24, '最后一幅画', '她画的最后一幅画。', 'https://i.postimg.cc/P5xjj34L/OB24.png'],
  [25, '她留下的一切', '所有的东西，都在。她不在了。', 'https://i.postimg.cc/vZNdHrqH/OB25.png'],
];

const EM_DATA: RawEntry[] = [
  [1, '心动', '你意识到，你心动了。', 'https://i.postimg.cc/TYjjrxBz/EM1.png'],
  [2, '嫉妒', '不想让别人靠近她。', 'https://i.postimg.cc/ncKKvxNg/EM2.png'],
  [3, '无力感', '什么都做不了的感觉。', 'https://i.postimg.cc/c477QWVy/EM3.png'],
  [4, '愤怒', '为什么是她。', 'https://i.postimg.cc/CLCCj0Wy/EM4.png'],
  [5, '否认', '"不可能。不会的。"', 'https://i.postimg.cc/DyQQqhth/EM5.png'],
  [6, '接受', '不是放弃，是不再逃避。', 'https://i.postimg.cc/c477QWVZ/EM6.png'],
  [7, '珍惜', '突然觉得每一秒都很重要。', 'https://i.postimg.cc/4NvvzGrT/EM7.png'],
  [8, '遗憾', '如果时间能再多一点。', 'https://i.postimg.cc/c477QWVx/EM8.png'],
  [9, '感恩', '谢谢你出现在她的生命里。', 'https://i.postimg.cc/zXwwnN9f/EM9.png'],
  [10, '恐惧', '你害怕那一天到来。', 'https://i.postimg.cc/Hs00Qmfn/EM10.png'],
  [11, '故作坚强', '在她面前，你不能哭。', 'https://i.postimg.cc/pXQQDvgm/EM11.png'],
  [12, '终于哭了', '你终于在没有人的地方哭了。', 'https://i.postimg.cc/sDPPpztS/EM12.png'],
  [13, '她也在装', '她也在装作没事。', 'https://i.postimg.cc/CxFG7tg5/EM13.png'],
  [14, '不装了', '两个人都不装了。', 'https://i.postimg.cc/Z5T8HgSB/EM14.png'],
  [15, '抱头痛哭', '你们抱在一起大哭了一场。', 'https://i.postimg.cc/jSsHc9by/EM15.png'],
  [16, '哭完了', '哭完之后，反而平静了。', 'https://i.postimg.cc/kgnQsZmF/EM16.png'],
  [17, '她笑了', '"好丢人。"', 'https://i.postimg.cc/VkYqgT8F/EM17.png'],
  [18, '你笑了', '"你比我丢人。"', 'https://i.postimg.cc/4xJ6PMgW/EM18.png'],
  [19, '不公平', '"凭什么。"', 'https://i.postimg.cc/rw81jbkZ/EM19.png'],
  [20, '她说值得', '"遇到你，值得了。"', 'https://i.postimg.cc/kgfxpcJF/EM20.png'],
  [21, '想让时间停下来', '如果这一秒能永远就好了。', 'https://i.postimg.cc/L8NzbT9N/EM21.png'],
  [22, '时间不会停', '但时间不会停。', 'https://i.postimg.cc/qvj85LJ5/EM22.png'],
  [23, '她很勇敢', '她比任何人都勇敢。', 'https://i.postimg.cc/7ZmgWVHj/EM23.png'],
  [24, '你也很勇敢', '选择陪在她身边。', 'https://i.postimg.cc/2S24KwjR/EM24.png'],
  [25, '后悔', '后悔没有更早说出口。', 'https://i.postimg.cc/13JpjHRQ/EM25.png'],
  [26, '不后悔', '但不后悔遇见她。', 'https://i.postimg.cc/XYQwz8N3/EM26.png'],
  [27, '想保护她', '想保护她不受任何伤害。', 'https://i.postimg.cc/zG0ncjDJ/EM27.png'],
  [28, '保护不了', '可有些东西你保护不了。', 'https://i.postimg.cc/3xngcBrr/EM28.png'],
  [29, '陪她就好', '保护不了，那就陪着。', 'https://i.postimg.cc/qvj85LBv/EM29.png'],
  [30, '牵着的手', '手一直牵着，从没松开过。', 'https://i.postimg.cc/cJCQyn6q/EM30.png'],
  [31, '最后一眼', '你看着她的最后一眼。', 'https://i.postimg.cc/R0hc5Hq4/EM31.png'],
  [32, '她看着你', '她看着你的最后一眼。', 'https://i.postimg.cc/VNvjQC5L/EM32.png'],
  [33, '说不出再见', '你说不出"再见"。', 'https://i.postimg.cc/k5Gx3bDG/EM33.png'],
  [34, '她替你说了', '"再见。"她笑着说的。', 'https://i.postimg.cc/mrkQfHhP/EM34.png'],
  [35, '空了', '她走了以后，什么都空了。', 'https://i.postimg.cc/25y4RZ3v/EM35.png'],
  [36, '门对面', '对面那扇不会再开的门。', 'https://i.postimg.cc/5tywdCjz/EM36.png'],
  [37, '风铃响了', '她挂的风铃响了。没有人碰它。', 'https://i.postimg.cc/FK609HJY/EM37.png'],
  [38, '你去看海了', '你一个人去了海边。', 'https://i.postimg.cc/3wq2KxD0/EM38.png'],
  [39, '潮汐还在', '潮水涨了又退，退了又涨。', 'https://i.postimg.cc/k5HWngtb/EM39.png'],
  [40, '月亮还在', '你抬头。月亮还在。', 'https://i.postimg.cc/CK2bFxfk/EM40.png'],
];

const FU_DATA: RawEntry[] = [
  [1, '白色', '那天所有人都穿了白色。', 'https://i.postimg.cc/kg80N272/FU1.png'],
  [2, '她穿的', '她最喜欢的那条连衣裙。', 'https://i.postimg.cc/Qd52gFjB/FU2.png'],
  [3, '很安详', '像在睡觉。', 'https://i.postimg.cc/FHcMbYh1/FU3.png'],
  [4, '花', '棺材里全是花。', 'https://i.postimg.cc/3xpsjk30/FU4.png'],
  [5, '她妈妈', '她妈妈握着她的手不放。', 'https://i.postimg.cc/g2RCyxGD/FU5.png'],
  [6, '她爸爸', '她爸爸一句话都说不出来。', 'https://i.postimg.cc/TP6ZtTPm/FU6.png'],
  [7, '你站在那里', '你站在那里，一动不动。', 'https://i.postimg.cc/vmsp0Gmz/FU7.png'],
  [8, '你没哭', '不是不想，是哭不出来。', 'https://i.postimg.cc/k5mkT751/FU8.png'],
  [9, '别人的眼泪', '所有人都在哭。', 'https://i.postimg.cc/pdHgsPd3/FU9.png'],
  [10, '你说了什么', '你对着她说了最后一句话。', 'https://i.postimg.cc/YSzTVT4D/FU10.png'],
  [11, '盖上了', '棺盖合上了。', 'https://i.postimg.cc/XvbTsnJb/FU11.png'],
  [12, '你想掀开', '你差点伸手去掀开它。', 'https://i.postimg.cc/k5vLZL69/FU12.png'],
  [13, '入土', '她入土了。', 'https://i.postimg.cc/W4wxKxF1/FU13.png'],
  [14, '你铲了第一锹土', '第一个铲土的人。', 'https://i.postimg.cc/VNW2T2rN/FU14.png'],
  [15, '墓碑', '墓碑上刻着她的名字和日期。', 'https://i.postimg.cc/hG1NwNzf/FU15.png'],
  [16, '十九岁', '永远停在了十八岁。', 'https://i.postimg.cc/XJNt0xd7/FU16.png'],
  [17, '墓前的花', '你在墓前放了一束花。', 'https://i.postimg.cc/DZfRK5LJ/FU17.png'],
  [18, '回家的路', '你一个人走回家。', 'https://i.postimg.cc/k4MLdwK8/FU18.png'],
  [19, '对面的门', '对面的门关着。', 'https://i.postimg.cc/ZRYXhjpx/FU19.png'],
  [20, '钥匙', '她妈妈把她房间的钥匙给了你。', 'https://i.postimg.cc/9MXsj1Zb/FU20.png'],
  [21, '进她的房间', '房间里还是她的味道。', 'https://i.postimg.cc/pTV3tkzc/FU21.png'],
  [22, '床上的画本', '停在你的画像那页。', 'https://i.postimg.cc/rmh3yWNC/FU22.png'],
  [23, '枕头下面', '枕头下面压着什么。', 'https://i.postimg.cc/bJ6WYb95/FU23.png'],
  [24, '给你的信', '写着"给你"。', 'https://i.postimg.cc/Kz9wcL5x/FU24.png'],
  [25, '读信', '你读了那封信。', 'https://i.postimg.cc/ZRf2Y3xD/FU25.png'],
  [26, '信的内容', '"活下去，替我看完所有风景。"', 'https://i.postimg.cc/zBd6DWF6/FU26.png'],
  [27, '你哭了', '你终于哭了。', 'https://i.postimg.cc/hvfwXj2k/FU27.png'],
  [28, '信纸湿了', '信纸被你的眼泪浸湿了。', 'https://i.postimg.cc/fyJFVLH4/FU28.png'],
  [29, '第49天', '四十九天了。每天都去看她。', 'https://i.postimg.cc/WzhKd39P/FU29.png'],
  [30, '9月1日', '开学了。"我生日是开学前一天。"', 'https://i.postimg.cc/j2L9D58j/FU30.png'],
];

const HI_DATA: RawEntry[] = [
  [1, '回到原点', '你回到了第一次见面的医院。', 'https://i.postimg.cc/2SsBJKpJ/HI1.png'],
  [2, '产房', '站在产房外面。', 'https://i.postimg.cc/sgkZ8NFL/HI2.png'],
  [3, '她的名字', '"潮汐"是因为出生那天在涨潮。', 'https://i.postimg.cc/Cx3ftQyX/HI3.png'],
  [4, '你的名字', '"你的名字也很好听。"', 'https://i.postimg.cc/Z5GygMtz/HI4.png'],
  [5, '身高差', '你比她高了整整一个头。', 'https://i.postimg.cc/TPnWXJGS/HI5.png'],
  [6, '她踮脚', '踮起脚尖才能亲到你。', 'https://i.postimg.cc/vm56dtMC/HI6.png'],
  [7, '一百张照片', '超过一百张照片。', 'https://i.postimg.cc/6QCGNfwk/HI7.png'],
  [8, '每天都见面', '连续二十天每天都见面了。', 'https://i.postimg.cc/CKbfVsSg/HI8.png'],
  [9, '零点', '在零点的时候还在一起。', 'https://i.postimg.cc/VNXbcWmJ/HI9.png'],
  [10, '同一句话', '同时说了一样的话。', 'https://i.postimg.cc/6QCGNft2/HI10.png'],
  [11, '同一首歌', '不约而同地哼了同一首歌。', 'https://i.postimg.cc/zfTR1F8R/HI11.png'],
  [12, '你学了做菜', '厨艺进步了。', 'https://i.postimg.cc/76DJPJZb/HI12.png'],
  [13, '你学了画画', '你也开始画画了。', 'https://i.postimg.cc/FRmkFkH3/HI13.png'],
  [14, '读了她推荐的书', '读完了旅行文学。', 'https://i.postimg.cc/xCYNjN1v/HI14.png'],
  [15, '你折了纸鹤', '你学会了折纸鹤。', 'https://i.postimg.cc/bJ8SYSwR/HI15.png'],
  [16, '给她的歌', '你给她找了一首歌。', 'https://i.postimg.cc/d1vZQZV4/HI16.png'],
  [17, '她的最爱', '终于知道她最喜欢的一切。', 'https://i.postimg.cc/Px4pCfCb/HI17.png'],
  [18, '她知道你的', '她其实早就知道你的一切。', 'https://i.postimg.cc/C1NBRMRH/HI18.png'],
  [19, '双向奔赴', '你们从来都是双向的。', 'https://i.postimg.cc/4d57Y4YP/HI19.png'],
  [20, '月亮与潮汐', '"你是月亮，我是潮汐。"', 'https://i.postimg.cc/Hx2crWrP/HI20.png'],
];

const AF_DATA: RawEntry[] = [
  [1, '空了的房间', '她的房间被整理了。', 'https://i.postimg.cc/x1RWpWN7/AF1.png'],
  [2, '她的衣服', '衣柜里还有她的衣服。', 'https://i.postimg.cc/K8Ndpd36/AF2.png'],
  [3, '她的香味', '衣服上还有她的味道。', 'https://i.postimg.cc/nhk6S696/AF3.png'],
  [4, '你养的猫', '猫还在。你替她养着。', 'https://i.postimg.cc/Bngd7d1f/AF4.png'],
  [5, '猫去了她房间', '猫在她的房间门口叫。', 'https://i.postimg.cc/QdbRYRWC/AF5.png'],
  [6, '秋天来了', '八月结束了，秋天来了。', 'https://i.postimg.cc/bwTKVK2G/AF6.png'],
  [7, '第一个没有她的季节', '秋天的落叶，她看不到了。', 'https://i.postimg.cc/N0jZ3p1G/AF7.png'],
  [8, '冬天', '下雪了。她说过想看雪。', 'https://i.postimg.cc/rpw7BQSs/AF8.png'],
  [9, '你替她看了', '你拍了雪景去墓前给她看。', 'https://i.postimg.cc/fbR1GBxJ/AF9.png'],
  [10, '春天', '花开了。又一年。', 'https://i.postimg.cc/YSCT5b1Y/AF10.png'],
  [11, '她种的花', '阳台上她种的花开了。', 'https://i.postimg.cc/k5gL0fxx/AF11.png'],
  [12, '你继续浇花', '你替她继续浇。', 'https://i.postimg.cc/KY8C6Jnf/AF12.png'],
  [13, '时间胶囊', '你挖出了时间胶囊。', 'https://i.postimg.cc/xdpBnMRK/AF13.png'],
  [14, '她放了什么', '一张纸条和一张照片。', 'https://i.postimg.cc/432jsV55/AF14.png'],
  [15, '纸条上写的', '"我很幸福。——洛潮汐"', 'https://i.postimg.cc/MG3gqVDr/AF15.png'],
  [16, '照片', '照片上是你的侧脸。', 'https://i.postimg.cc/SK1HkCrB/AF16.png'],
  [17, '你去看海了', '一个人去了那片海。', 'https://i.postimg.cc/N0CZBmDw/AF17.png'],
  [18, '潮汐', '潮水还是那样涨涨落落。', 'https://i.postimg.cc/N0CZBmDt/AF18.png'],
  [19, '你坐在沙滩上', '坐在她坐过的地方。', 'https://i.postimg.cc/Jnyvn0YV/AF19.png'],
  [20, '浪花碰脚', '潮水漫过你的脚踝。', 'https://i.postimg.cc/4dKqdy2Z/AF20.png'],
  [21, '你闭上了眼睛', '好像她还在旁边。', 'https://i.postimg.cc/0Q6FQjXP/AF21.png'],
  [22, '日出', '你看了一次日出。替她。', 'https://i.postimg.cc/j5Wm523d/AF22.png'],
  [23, '画', '你试着画了一幅画。画的是她。', 'https://i.postimg.cc/fL3pLyq3/AF23.png'],
  [24, '画得不好', '画得很丑。但你画了。', 'https://i.postimg.cc/xCkhC8pJ/AF24.png'],
  [25, '折纸鹤', '你开始折纸鹤了。', 'https://i.postimg.cc/85F95cXr/AF25.png'],
  [26, '一千只', '你折完了一千只纸鹤。', 'https://i.postimg.cc/PxL9xJVD/AF26.png'],
  [27, '许愿', '你许了一个愿望。', 'https://i.postimg.cc/XJZmJq19/AF27.png'],
  [28, '活下去', '你活下去了。', 'https://i.postimg.cc/W3QKJVx3/AF28.png'],
  [29, '看完所有风景', '你替她看完了所有风景。', 'https://i.postimg.cc/xCW7bQBc/AF29.png'],
  [30, '潮汐不息', '潮去汐来。她一直在。', 'https://i.postimg.cc/QtRPWDvT/AF30.png'],
];

const FI_DATA: RawEntry[] = [
  [1, '潮汐永眠', '手捧鲜花，她安静地躺在那里。像小时候午睡在你家沙发上的样子。只是这一次，不会再醒来。', 'https://i.postimg.cc/BZ7bkVHg/FL1.png'],
];

// 将原始数据转换为 AchievementEntry
function buildEntries(prefix: string, data: RawEntry[]): AchievementEntry[] {
  return data.map(([num, name, desc, img]) => ({
    id: makeId(prefix, num),
    name,
    desc,
    img,
  }));
}

// 所有成就按篇章分组
export const ACHIEVEMENT_MAP: Record<string, AchievementEntry[]> = {
  RE: buildEntries('RE', RE_DATA),
  DA: buildEntries('DA', DA_DATA),
  WI: buildEntries('WI', WI_DATA),
  LO: buildEntries('LO', LO_DATA),
  TR: buildEntries('TR', TR_DATA),
  ME: buildEntries('ME', ME_DATA),
  IL: buildEntries('IL', IL_DATA),
  TI: buildEntries('TI', TI_DATA),
  SP: buildEntries('SP', SP_DATA),
  OB: buildEntries('OB', OB_DATA),
  EM: buildEntries('EM', EM_DATA),
  FU: buildEntries('FU', FU_DATA),
  AF: buildEntries('AF', AF_DATA),
  HI: buildEntries('HI', HI_DATA),
  FI: buildEntries('FI', FI_DATA),
};

// 根据ID快速查找
const _flatMap = new Map<string, AchievementEntry>();
for (const entries of Object.values(ACHIEVEMENT_MAP)) {
  for (const entry of entries) {
    _flatMap.set(entry.id, entry);
  }
}

export function getAchievementById(id: string): AchievementEntry | undefined {
  return _flatMap.get(id);
}
