/** 41种差分表情 → 图片URL映射 */
export const EXPRESSION_MAP: Record<string, string> = {
  微笑: 'https://i.postimg.cc/RF5GXyY7/1.png',
  开心: 'https://i.postimg.cc/KzSQJwWn/2.png',
  大笑: 'https://i.postimg.cc/cHyTX2zM/3.png',
  害羞: 'https://i.postimg.cc/k43wfzHv/4.png',
  平静: 'https://i.postimg.cc/3R59nVqP/5.png',
  思考: 'https://i.postimg.cc/63rcSzsY/6.png',
  惊讶: 'https://i.postimg.cc/HxwzK3G6/7.png',
  疑惑: 'https://i.postimg.cc/HxwzK3GZ/8.png',
  温柔: 'https://i.postimg.cc/HxwzK3Dm/9.png',
  思念: 'https://i.postimg.cc/XJfLhxSN/10.png',
  撒娇: 'https://i.postimg.cc/rm1jbgXm/11.png',
  调皮: 'https://i.postimg.cc/tT3kfDQY/12.png',
  心动: 'https://i.postimg.cc/0j9nqmP5/13.png',
  深情凝视: 'https://i.postimg.cc/T1T0Xmf3/14.png',
  依赖: 'https://i.postimg.cc/kG7sd8q5/15.png',
  轻伤感: 'https://i.postimg.cc/tJ9kHPp7/16.png',
  难过: 'https://i.postimg.cc/QCjmr5h9/17.png',
  哭泣: 'https://i.postimg.cc/MHz58Rqj/18.png',
  痛哭: 'https://i.postimg.cc/Wzs8PrTZ/19.png',
  心痛: 'https://i.postimg.cc/tJ9kHPpW/20.png',
  强忍: 'https://i.postimg.cc/tJ9kHPpz/21.png',
  释然: 'https://i.postimg.cc/BbJpGD4N/22.png',
  疲倦: 'https://i.postimg.cc/mkVwZDgQ/23.png',
  虚弱: 'https://i.postimg.cc/d3nBQ1Vm/24.png',
  气短: 'https://i.postimg.cc/cCTm1HLF/25.png',
  晕眩: 'https://i.postimg.cc/prkZVTLc/26.png',
  病中微笑: 'https://i.postimg.cc/yxnP6d8b/27.png',
  沉睡: 'https://i.postimg.cc/D05gfZwt/28.png',
  被风吹: 'https://i.postimg.cc/Xqx8NJvW/29.png',
  看海: 'https://i.postimg.cc/ZYLjxfx5/30.png',
  看烟花: 'https://i.postimg.cc/bYRL969v/31.png',
  雨中: 'https://i.postimg.cc/fWv5fHfm/32.png',
  夕阳下: 'https://i.postimg.cc/xjPg3s3v/33.png',
  月光下: 'https://i.postimg.cc/XNgxk2kk/34.png',
  吃东西: 'https://i.postimg.cc/RCTGLPLR/35.png',
  画画中: 'https://i.postimg.cc/ncc2Rv31/36.png',
  浴衣: 'https://i.postimg.cc/qMMwb81Q/37.png',
  举起相机: 'https://i.postimg.cc/X77LHwsD/38.png',
  最后的笑: 'https://i.postimg.cc/2S9kwBck/39.png',
  告别: 'https://i.postimg.cc/gkksSvg1/40.png',
  安详: 'https://i.postimg.cc/sDDm6pnd/41.png',
};

/** 表情分类标签 */
export const EXPRESSION_CATEGORIES: Record<string, string[]> = {
  日常: ['微笑', '开心', '大笑', '害羞', '平静', '思考', '惊讶', '疑惑'],
  温情: ['温柔', '思念', '撒娇', '调皮', '心动', '深情凝视', '依赖'],
  伤感: ['轻伤感', '难过', '哭泣', '痛哭', '心痛', '强忍', '释然'],
  身体: ['疲倦', '虚弱', '气短', '晕眩', '病中微笑', '沉睡'],
  场景: ['被风吹', '看海', '看烟花', '雨中', '夕阳下', '月光下', '吃东西', '画画中', '浴衣', '举起相机'],
  终章: ['最后的笑', '告别', '安详'],
};

/** 成就篇章信息：前缀 → 篇章名/总数/颜色 */
export const CHAPTER_INFO: Record<string, { name: string; total: number; color: string }> = {
  RE: { name: '初遇', total: 30, color: '#a8d4e6' },
  DA: { name: '日常', total: 80, color: '#5b8fb9' },
  WI: { name: '愿望', total: 49, color: '#f0c987' },
  LO: { name: '感情', total: 100, color: '#d4878f' },
  TR: { name: '旅行', total: 50, color: '#7bc8a4' },
  ME: { name: '记忆', total: 40, color: '#c9a0dc' },
  IL: { name: '病情', total: 60, color: '#9bb0c4' },
  TI: { name: '日期', total: 31, color: '#b8d4e6' },
  SP: { name: '特殊', total: 25, color: '#e8a87c' },
  OB: { name: '物件', total: 25, color: '#c4b89a' },
  EM: { name: '情绪', total: 40, color: '#8bacc7' },
  FU: { name: '葬礼', total: 30, color: '#6b8299' },
  AF: { name: '余生', total: 30, color: '#7bc8a4' },
  HI: { name: '隐藏', total: 20, color: '#c9d6df' },
  FI: { name: '终章', total: 1, color: '#2c4a6e' },
};

