export const Schema = z.object({
  交易次数: z.coerce.number().transform(value => Math.max(0, Math.floor(value))).prefault(0),
  本周交易次数: z.coerce.number().transform(value => Math.max(0, Math.floor(value))).prefault(0),
  奥妮安存款: z.coerce.number().transform(value => Math.floor(value)).prefault(500),
  当前场景: z.enum([
    '学校教室',
    '学校天台',
    '学校走廊',
    '学校食堂',
    '学校厕所',
    '学校体育馆',
    '学校图书馆',
    '{{user}}家客厅',
    '{{user}}家卧室',
    '{{user}}家浴室',
    '{{user}}家阳台',
    '便利店',
    '奥妮安家',
    '地铁上',
    '公园长椅',
    '电影院',
    '商场',
    '天桥下',
    '小巷子',
    '街道',
  ]).prefault('学校天台'),
  星期: z.enum(['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日']).prefault('星期三'),
  时间段: z.enum(['早晨', '上午', '中午', '下午', '傍晚', '晚上', '深夜']).prefault('中午'),
  特殊事件: z.enum(['无', '差点被发现', '体育课后', '雨天湿身', '极度缺钱']).prefault('无'),
  关系状态: z.enum(['交易对象', '特殊存在', '暧昧', '恋人']).prefault('交易对象'),
});

export type Schema = z.output<typeof Schema>;
